#cloud-config
packages:
  - haproxy

package_update: true
package_upgrade: true

users:
  - name: admin
    homedir: /admin
    groups: users, adm, wheel, systemd-journal
    selinux_user: unconfined_u
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: [
      # ADD YOUR SSH KEYS HERE FOR RECOVERY
    ]
  - name: bastion
    groups: users, adm, wheel, systemd-journal
    selinux_user: unconfined_u
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: [
      # ADD a bastion group's egress SSH pub key here to allow SSH from bastion
    ]

write_files:
  - path: /etc/haproxy/haproxy.cfg
    content: |
      global
        daemon
        maxconn 256

      defaults
        mode tcp
        timeout connect 10s
        timeout client  1m
        timeout server  1m

      frontend k8s_api
        bind *:6443
        default_backend k8s_api_backend

      backend k8s_api_backend
        balance roundrobin
        %{ for idx, ip in ip_addrs ~}
        server cp${idx + 1} ${ip}:6443 check
        %{ endfor ~}

runcmd:
  - semanage port -a -t http_port_t -p tcp 6443
  - systemctl restart haproxy
