#cloud-config
users:
  - name: admin
    groups: adm, wheel, systemd-journal
    selinux_user: unconfined_u
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: [
      # TODO: add Bastion key once setup
    ]
